  
version: '3.5'
services:
  mongo:
    image: mongo:3.6.18-xenial
    container_name: mongo-database
    restart: always
    ports:
      - 27017:27017
    # network_mode: host
    volumes:
      - $HOME/mongo:/data/db
    healthcheck:
      test: "exit 0"
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - localhost      


  user-service:
    build: user-service/
    image: user-service
    depends_on:
      - mongo
    # network_mode: "host"
    # hostname: localhost
    restart: always
    ports:
      - 8082:8082
    healthcheck:
      test: "exit 0"
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - localhost      

# Networks to be created to facilitate communication between containers
networks:
  localhost:      