server:
    port: 8082
spring:
    application:
        name: service-app
    data:
        mongodb:
            uri: mongodb://mongo-database:27017/user
    datasource:
        driver-class-name: mongodb.jdbc.MongoDriver
app:
    exceptionMessage: User already exists!
    globalExceptionMessage: Database connectivity lost!

logging:
  level:
    root: ERROR
    org.springframework.web: DEBUG    
    org.hibernate: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG